## Acrylicä¸»é¢˜é…ç½®æ–‡ä»¶
############################################################################################################
# ä¸ºé¿å…ä¸»é¢˜æ›´æ–°åï¼Œé…ç½®æ–‡ä»¶è¢«è¦†ç›–ï¼Œè¯·å¤åˆ¶ä¸€ä»½æ­¤æ–‡ä»¶åˆ°ç«™ç‚¹æ ¹ç›®å½•ä¸‹çš„_config.Acrylic.ymlæ–‡ä»¶ä¸­ï¼Œä¿®æ”¹_config.Acrylic.ymlæ–‡ä»¶ä¸­çš„é…ç½®
############################################################################################################
# ä¿®æ”¹æ­¤æ–‡ä»¶å‰ï¼Œè¯·ä»”ç»†é˜…è¯»å®˜æ–¹æ–‡æ¡£ï¼šhttps://next-docs.acrylic.org.cn/
############################################################################################################


# ç«™ç‚¹è®¾ç½®
site:
  name:                   # å·¦ä¸Šè§’æ˜¾ç¤ºå†…å®¹
    class:  text          #i_class/text/img 
    custom: Açº§èµ„æºç½‘      #è‡ªå®šä¹‰å†…å®¹
  siteIcon: /img/favicon.jpg # ç½‘é¡µicon
  icon: /img/avatar.webp     # é¡µè„šçš„iconã€åŠ è½½åŠ¨ç”»é»˜è®¤çš„icon
  categories:
    data:
      - name: ğŸ”¥çƒ­é—¨
        path: /tags/çƒ­é—¨/
      - name: å·¥å…·
        path: /tags/å·¥å…·/
        children:
          - name: åœ¨çº¿å°å·¥å…·
            path: /tags/åœ¨çº¿å°å·¥å…·/
          - name: AIå·¥å…·
            path: /tags/AIå·¥å…·/
      - name: å½±éŸ³
        path: /tags/å½±éŸ³/
        children:
          - name: è§†é¢‘
            path: /tags/è§†é¢‘/
          - name: éŸ³ä¹
            path: /tags/éŸ³ä¹/
      - name: è½¯ä»¶
        path: /tags/è½¯ä»¶/
        children:
          - name: macè½¯ä»¶
            path: /tags/macè½¯ä»¶/
          - name: iosè½¯ä»¶
            path: /tags/iosè½¯ä»¶/
          - name: windowsè½¯ä»¶
            path: /tags/windowsè½¯ä»¶/
          - name: å®‰å“è½¯ä»¶
            path: /tags/å®‰å“è½¯ä»¶/
      - name: ç½‘èµš
        path: /tags/ç½‘èµš/
      - name: æ•™ç¨‹
        path: /tags/æ•™ç¨‹/
      - name: ç”Ÿå­˜ä¹‹é“
        path: /tags/ç”Ÿå­˜ä¹‹é“
      - name: ç¦åˆ©
        path: /tags/ç¦åˆ©/
  tags:
    data:
      - name: è°·æ­Œ444
        path: https://www.baidu.com
  posts:
    data:
      - path: https://www.baidu.com
        title: SAP HANAé¡¹ç›®è¿‡ç¨‹ä¸­ä¼˜åŒ–åˆ†æä»¥åŠå¯è¡Œæ€§éªŒè¯
        cover: /img/avatar.webp
        recommend: true
  icp:                       # ICP

# å¯¼èˆªæ 
nav:
#å¯¼èˆªæ å·¦ä¾§
  left:
    enable: true
    menu:
      # æˆ‘çš„:
      #   åšå®¢:
      #     icon: /img/avatar.webp
      #     url: /
# å¯¼èˆªæ å†…å®¹
  menu:
    æ–‡åº“:
      url: false
      child:
        æ–‡ç« åˆ—è¡¨:
          url: /archives/
          icon: fas fa-box-archive
        å…¨éƒ¨åˆ†ç±»:
          url: /categories/
          icon: fas fa-cube
        # å…¨éƒ¨æ ‡ç­¾:
        #   url: /tags/
        #   icon: fas fa-tags
    å‹é“¾:
      url: false
      child:
        bootcss:
          url: https://www.bootcss.com
          icon: fa-brands fa-bootstrap 
        nodejs:
          url: https://nodejs.org
          icon: fa-brands fa-node-js
        # å‹é“¾é±¼å¡˜:
        #   url: /fcircle/
        #   icon: fas fa-fish-fins
      #   å‹æƒ…é“¾æ¥:
      #     url: /links/
      #     icon: fas fa-user-group
      #   å®è—åšä¸»:
      #     url: javascript:travelling()
      #     icon: fas fa-bus

# å¯¼èˆªæ å³ä¾§å¿«æ·èœå•
  right: # @todo å…è®¸ç”¨æˆ·è‡ªå®šä¹‰
    travellings: false   #å¼€å¾€
    random: true        #
    console: true       #æ§åˆ¶å°

# heoå¼é¡¶éƒ¨ä¸€å¤§å¨
hometop:
  bbtime: false
  banner:
    enable: true
    # title: åˆ†äº«è®¾è®¡<br>ä¸ç§‘æŠ€ç”Ÿæ´»
    title: æ¢ç´¢æœªçŸ¥é¢†åŸŸçš„<br>ç¥ç§˜å®åº“ï¼
    url: www.abfunny.com
    icon:
      AE:
        img: /img/icon/ae.png
        color: '#989bf8'
      Sketch:
        img: /img/icon/Sketch.png
        color: '#ffffff'
      Docker:
        img: /img/icon/docker.png
        color: '#57b6e6'
      ps:
        img: /img/icon/ps.png
        color: '#4082c3'
      FinalCutPro:
        img: /img/icon/FinalCutPro.png
        color: '#ffffff'
      Python:
        img: /img/icon/Python.png
        color: '#ffffff'
      Swift:
        img: /img/icon/Swift.png
        color: '#eb6840'
      Principle:
        img: /img/icon/Principle.png
        color: '#8f55ba'
      illustrator:
        img: /img/icon/illustrator.png
        color: '#f29e39'
      CSS3:
        img: /img/icon/CSS3.png
        color: '#2c51db'
      JS:
        img: /img/icon/JS.png
        color: '#f7cb4f'
      Git:
        img: /img/icon/git.png
        color: '#df5b40'

  categoryGroup:
    G1:
      name: åœ¨çº¿å·¥å…·
      icon: fas fa-dove
      url: /tags/åœ¨çº¿å°å·¥å…·/
    G2:
      name: çƒ­é—¨æ–‡ç« 
      icon: fas fa-burn
      url: /tags/çƒ­é—¨/
    G3:
      name: å®ç”¨æ•™ç¨‹
      icon: fas fa-book
      url: /tags/å¤§äººå­¦ä¹ è¯¾ç¨‹/

  recommendList:
    sup: æˆ‘ä»¬çš„slogan
    title: èµ„æºå…±äº«ï¼Œè®©ç”Ÿæ´»æ›´ç¾å¥½ï¼
    url: /tags/çƒ­é—¨/
    img: /img/stocksnap.jpg
    color: '#006a73'

# ä¸ªäººå¡ç‰‡
aside:
  home:
    noSticky: "about,flip"
    Sticky: "newestPost,allInfo"
  post:
    noSticky: "about"
    Sticky: "newestPost"
  page:
    noSticky: "about,flip"
    Sticky: "newestPost,allInfo"

  card:
    avatar: 
    # content: è¿™æœ‰å…³äº<b>å¼€å‘</b>ã€<b>æŠ€æœ¯</b>ç›¸å…³çš„é—®é¢˜å’Œçœ‹æ³•ï¼Œè¿˜æœ‰å¯¹äºåŠ¨æ¼«çš„ä¸€äº›<b>æ‚è¯„</b>ã€‚<br>ç›¸ä¿¡ä½ å¯ä»¥åœ¨è¿™é‡Œæ‰¾åˆ°å¯¹ä½ æœ‰ç”¨çš„çŸ¥è¯†å’Œæ•™ç¨‹ã€‚
    content: è¯´æ˜ï¼šæœ¬ç«™æ‰€æœ‰èµ„æºå‡æ¥æºäºäº’è”ç½‘ï¼Œ<b>å…¨éƒ¨å…è´¹</b>ï¼éƒ¨åˆ†å…·æœ‰<b>æ—¶æ•ˆæ€§</b>ï¼<br><br>ç›¸ä¿¡ä½ å¯ä»¥åœ¨è¿™é‡Œæ‰¾åˆ°å¯¹ä½ æœ‰ç”¨çš„çŸ¥è¯†å’Œæ•™ç¨‹ã€‚
    information:
      # Github:
      #   icon: fa-brands fa-github
      #   url: https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next
      Telegram:
        icon: fa-brands fa-telegram
        url: https://t.me/lvlvwzy
      Mail:
        icon: fa-solid fa-envelope
        url: mailto:a@nalex.top
    button:
      text: ä¸ªäººä¸»é¡µ
      url: /

  flip:
    color: '#0099FF'
    face:
      title: QQç¾¤
      desc: åŠ å…¥å®˜æ–¹QQç¾¤ä¸æˆ‘ä»¬äº¤æµ
    backface:
      title: æ‰«ä¸€æ‰«
      desc: è·å–æœ€æ–°ä¿¡æ¯å’Œå¸®åŠ©
      img: /img/my-qq.jpeg

  toc: 
    post: true
    page: false

  # å»ºç«™æ—¶é—´
  siteinfo:
    postcount: true
    wordcount: false
    pv: false
    uv: false
    updatetime: false
    runtimeenable: true
    runtime: '2021-12-12 00:00:00'

# é¡µè„š
footer:
  information:
    left:
      # Github:
      #   icon: fa-brands fa-github
      #   url: /
      Mail:
        icon: fa-solid fa-envelope
        url: mailto:lvlv49307@gmail.com
    right:
      Telegram:
        icon: fa-brands fa-telegram
        url: https://t.me/lvlvwzy
      bilibili:
        icon: fa-brands fa-twitter
        url: https://x.com/wang_yi67218

  group:
    å¯¼èˆª:
      æ–‡ç« å½’æ¡£: /archives/
      æ–‡ç« åˆ†ç±»: /categories/
      # æ–‡ç« æ ‡ç­¾: /tags/
      # å‹é“¾: /link/
    æœåŠ¡:
      ç™¾åº¦ç»Ÿè®¡: https://tongji.baidu.com/
      TianliCDN: https://ql.tianli0.top/
    # Acrylic:
    #   ä¸»é¢˜å®˜ç½‘: https://acrylic.zhheo.com/
    #   Github: https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic
    #   Heo: https://blog.zhheo.com/
    å‹é“¾:
      ç™¾åº¦: https://www.baidu.com/
      è°·æ­Œ: https://www.google.com/

  randomlink: false

  cdn:
    url: 
    desc: 
  rss:
    url: 
  license:
    url: https://creativecommons.org/licenses/by/4.0/
    icon: fas fa-closed-captioning


page:
  error: true
  tags: true
  categories: true
  default:
    cover: /img/hello.jpg   

# æ–‡ç« é¡µé»˜è®¤è®¾ç½®
post:
  default:
    cover: /img/hello.jpg
    locate: åŒ—äº¬
    copyright: åŸåˆ›
  meta:
    date: true
    updated: true
    locate: false
    wordcount: false
    readtime: false
    pv: false
    comment: false      
  award:
    enable: false
    wechat:
    alipay:
    url:
  covercolor: #æ–‡ç« coverå–è‰²  
    enable: false
    local: false  

# å…³äºç•Œé¢
about: false

# 404é¡µé¢
errorpage:
  img: /img/404.jpg
  text: =awa= é¡µé¢èµ°ä¸¢äº†
  recommendList: true

# æ‡’åŠ è½½
lazyload:
  enable: false
  placeholder: /img/acrylic.png
  errorimg: /img/acrylic.png

# å›¾ç‰‡ç¯ç®±
lightbox: true

#ä»£ç é«˜äº®å¢å¼º
hightlight:
  enable: false
  hightlimit: 200

# åŠ è½½åŠ¨ç”»
loading:
  fullpage: false
  pace: false
  enable: false
  img: https://bu.dusays.com/2023/07/15/64b2499a6ad24.png

# ç¬¬ä¸‰æ–¹è®¾ç½®
thirdparty:
  wordcount: false
  busuanzi: 
    enable: false
    usecomment: false #å½“è¯„è®ºç³»ç»Ÿå¼€å¯æ—¶æ–‡ç« é¡µé¢ä½¿ç”¨è¯„è®ºç³»ç»Ÿçš„ç»Ÿè®¡æ•°æ®
  search:
    algolia_search:
      enable: false
      # hits:
      #   per_page: 6
    local_search:
      enable: true
      preload: true
      CDN:
    
  aplayer:
    enable: false
    server: tencent
    id: 1708664797  
    api: "https://music.startly.cn/?server=:server&type=:type&id=:id&auth=:auth&r=:r" #è‡ªå®šä¹‰api    
  #ä¸­æ§å°æ‹“å±•
  consolePlus: true

# è¯„è®º
comment:
  enable: false
  twikoo:
    envId:
    # region: ap-shanghai
    path: window.location.pathname

# æ’å…¥ä»£ç åˆ°å¤´éƒ¨ </head> ä¹‹å‰ å’Œ åº•éƒ¨ </body> ä¹‹å‰
# æ’å…¥é¢å¤–ä»£ç  å¦‚ï¼šç»Ÿè®¡ï¼Œå¹¿å‘Šç­‰
extends: 
  head: # åœ¨headä¸­æ’å…¥
    - <script async src="https://www.googletagmanager.com/gtag/js?id=G-0BXB1NFBFS"></script>
    - <script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'G-0BXB1NFBFS');</script>
  body: # åœ¨bodyä¸­æ’å…¥

# éå¿…è¦å‹¿åŠ¨
cdn:
  head:
    pacejs: https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/pace/1.2.4/pace.min.js
    fontawesomecss: https://cdn.bootcdn.net/ajax/libs/font-awesome/6.3.0/css/all.min.css
    snackbarcss: /lib/snackbar.min.css
    qrcodejs: /lib/qrcode.min.js
    twikoojs: https://cdn.staticfile.org/twikoo/1.6.10/twikoo.all.min.js
    instantsearch: https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/instantsearch.js/4.39.0/instantsearch.production.min.js
    algolia: https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/algoliasearch/4.12.1/algoliasearch-lite.umd.min.js
  body:
    swipercss: /lib/swiper.min.css
    pjaxjs: /lib/pjax.min.js
    lazyloadjs: /lib/lazyload.min.js
    snackbarjs: /lib/snackbar.min.js
    viewimagejs: /lib/view-image.min.js
    waterfalljs: /lib/waterfall.min.js
    swiperjs: /lib/swiper.min.js
    busuanzijs: https://npm.elemecdn.com/penndu@1.0.0/bsz.js
    aplayercss: https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/aplayer/1.10.1/APlayer.min.css
    aplayerjs: https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/aplayer/1.10.1/APlayer.min.js
    metingjs: lib/meting.min.js